# Generated by Django 5.0.7 on 2024-09-02 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GermanWord",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=200, unique=True)),
                ("article", models.CharField(max_length=200)),
                ("word_type", models.CharField(max_length=200)),
                ("translation_1", models.CharField(max_length=200)),
                ("translation_2", models.CharField(max_length=200)),
                ("translation_3", models.CharField(max_length=200)),
                ("sentence_1", models.CharField(max_length=200)),
                ("sentence_2", models.CharField(max_length=200)),
                ("sentence_3", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "green_cards",
                    models.ManyToManyField(
                        related_name="game_sessions_green", to="game.germanword"
                    ),
                ),
                (
                    "red_cards",
                    models.ManyToManyField(
                        related_name="game_sessions_red", to="game.germanword"
                    ),
                ),
                (
                    "unclassified_cards",
                    models.ManyToManyField(
                        related_name="game_sessions_unc", to="game.germanword"
                    ),
                ),
                (
                    "yellow_cards",
                    models.ManyToManyField(
                        related_name="game_sessions_yellow", to="game.germanword"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                (
                    "last_day_played",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
