# Generated by Django 5.0.7 on 2024-10-01 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_cards', models.IntegerField(default=0, verbose_name='Number of green cards')),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='Number of yellow cards')),
                ('red_cards', models.IntegerField(default=0, verbose_name='Number of red cards')),
                ('total_time_played', models.IntegerField(default=0, verbose_name='Total time played')),
                ('total_responses', models.IntegerField(default=0, verbose_name='Total responses')),
                ('highest_score', models.IntegerField(default=0, verbose_name='Highest score')),
                ('highest_answer_streak', models.IntegerField(default=0, verbose_name='Highest answer streak')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='stats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.gamesessionstats'),
            preserve_default=False,
        ),
    ]
