# Generated by Django 5.0.7 on 2024-10-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesessionstats_gamesession_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='isEmpty',
            field=models.BooleanField(default=True, verbose_name='Is empty'),
        ),
        migrations.AddField(
            model_name='gamesessionstats',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
    ]
