# Generated by Django 5.0.7 on 2024-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_gamesessionstats_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessionstats",
            name="blocked",
            field=models.BooleanField(default=True, verbose_name="Is blocked"),
        ),
        migrations.AddField(
            model_name="gamesessionstats",
            name="points",
            field=models.IntegerField(default=0, editable=False, verbose_name="Points"),
        ),
    ]
