# Generated by Django 5.0.7 on 2024-12-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_germanword_sentence_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
