# Generated by Django 5.0.7 on 2024-12-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_germanword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessionstats',
            name='lowest_game_time',
            field=models.IntegerField(default=0, verbose_name='Lowest game time'),
        ),
    ]
