# Generated by Django 5.0.7 on 2025-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamesessionstats_lowest_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessionstats',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
